name = "Cobbleworld"
author = "Hikiru"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00527ce3ad9196add2620615c15f2f03e17b9f5c3ebae5d40e6ab5e8b2c6684c"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
