name = "Cobbleworld Alpha"
author = "Hikiru"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "959ef16a3f9024293f4ed907b0246f909fc7a1d35ffdf47c0da8a6afd35e41f2"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
