name = "Cobbleworld Alpha"
author = "Hikiru"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "266555fb0cfbff6787d4cd4eccd4b61c2f72d3b0bbe0854810fa79f7c414eea7"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
