name = "Cobbleworld"
author = "Hikiru"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe0c7b59fdaf81b407b25204af4c0f3283f6bf94fb844c14d8a3be2eabf24d53"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
