name = "Cobbleworld"
author = "Hikiru"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd1ab869c91c19e5aff7983cf30861bcca2665a93001d0a19384c9ddfc642f9"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
